/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class util */

#ifndef _Included_util
#define _Included_util
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     util
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_initialize
  (JNIEnv *, jobject);

/*
 * Class:     util
 * Method:    update_centres
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_util_update_1centres
  (JNIEnv *, jobject, jint);

/*
 * Class:     util
 * Method:    mmap_write
 * Signature: (JJ)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_util_mmap_1write
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     util
 * Method:    mmap_read
 * Signature: (I)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_util_mmap_1read
  (JNIEnv *, jobject, jint);

/*
 * Class:     util
 * Method:    write
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_write
  (JNIEnv *, jobject);

/*
 * Class:     util
 * Method:    read
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_util_read
  (JNIEnv *, jobject, jint);

/*
 * Class:     util
 * Method:    cleanup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_util_cleanup
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
